### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by TylorTurner** [mrfdev/MFM#1]
![image](https://github.com/user-attachments/assets/bddc0181-e1e0-414f-8de3-8500c87712cd)
Usnure if this is an issue

**Comment by mrfloris** [comment]
This is my personal github, not zrips', and I am not zrips. 
You're looking for this one: https://github.com/Zrips/MobFarmManager/issues

**Comment by TylorTurner** [comment]
MY BAD lol
